# Generated by Django 5.0.4 on 2024-04-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('AD', 'Admin'), ('DL', 'Delivery Person'), ('CL', 'Client')], default='CL', max_length=2),
        ),
    ]
