# Generated by Django 5.0.4 on 2024-05-04 09:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_favoriteitem_account_favorite_delete_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoriteitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
