# Generated by Django 5.0.4 on 2024-05-17 23:08

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_favoriteitem_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, default='account/accounts_images/default.jpg', null=True, upload_to=account.models.image_path, verbose_name='Profile Image'),
        ),
    ]
