# Generated by Django 5.0.4 on 2024-04-27 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_cart_add_date_cartitem_alter_cart_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items',
        ),
    ]
