# Generated by Django 5.0.4 on 2024-04-27 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_remove_cart_items'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
