# Generated by Django 5.0.4 on 2024-04-27 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_cart_cartitem_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='number of units'),
        ),
    ]
