# Generated by Django 5.0.4 on 2024-05-11 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_options_alter_message_sent_to'),
        ('item', '0011_cart_delivered_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chat.message'),
        ),
    ]
