# Generated by Django 5.0.4 on 2024-05-20 11:56

import item.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_cart_canceled_cart_canceled_by_cart_delivered_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='item/item_images/default.jpg', upload_to=item.models.item_image_path),
        ),
    ]
