# Generated by Django 5.0.4 on 2024-05-04 09:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='send_by',
            new_name='sent_by',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='send_to',
            new_name='sent_to',
        ),
        migrations.AddField(
            model_name='message',
            name='sent',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='chat.chat'),
        ),
    ]
