# Generated by Django 5.0.4 on 2024-05-14 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_options_alter_message_sent_to'),
        ('item', '0013_category_item_last_modified_alter_cart_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='cart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat', to='item.cart'),
        ),
    ]
